import { useRef, useState, useEffect } from "react";
import { motion, useScroll, useTransform, useSpring, useInView, AnimatePresence } from "framer-motion";
import { Link } from "react-router-dom";
import { PageLayout } from "@/components/layout/PageLayout";

const SAND   = "#C5A882";
const SAND_AA = "#9A7550";
const CREAM  = "#F5F0E8";
const STONE  = "#E8E0D4";
const DARK   = "#1D1D1B";
const PEARL  = "#C8B99A";
const GULF   = "#2A5F7A";

/* ── CountUp ── */
function CountUp({ value, delay = 0 }: { value: string; delay?: number }) {
  const [display, setDisplay] = useState(value);
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true });
  useEffect(() => {
    if (!inView) return;
    const num = parseInt(value.replace(/[^0-9]/g, ""));
    if (isNaN(num) || num === 0) { setDisplay(value); return; }
    let start = 0;
    const step = Math.ceil(num / 40);
    const t = setTimeout(() => {
      const id = setInterval(() => {
        start += step;
        if (start >= num) { setDisplay(value); clearInterval(id); }
        else setDisplay(value.replace(/[0-9,]+/, start.toLocaleString()));
      }, 30);
    }, delay * 1000);
    return () => clearTimeout(t);
  }, [inView]);
  return <span ref={ref}>{display}</span>;
}

/* ── TiltCard ── */
function TiltCard({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  const onMove = (e: React.MouseEvent<HTMLDivElement>) => {
    const r = ref.current!.getBoundingClientRect();
    setTilt({ x: ((e.clientY - r.top) / r.height - 0.5) * -10, y: ((e.clientX - r.left) / r.width - 0.5) * 10 });
  };
  return (
    <div ref={ref} onMouseMove={onMove} onMouseLeave={() => setTilt({ x: 0, y: 0 })} className={className}
      style={{ transform: `perspective(600px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`, transition: "transform 0.15s ease", willChange: "transform" }}>
      {children}
    </div>
  );
}

/* ── Stats ── */
const TOWER_STATS = [
  { n: "412.6", u: "m",  icon: "↑", l: "Height to tip",            sub: "Occupied height: 371.4m"          },
  { n: "80",    u: "",   icon: "▦", l: "Total levels",              sub: "62 dedicated office floors"        },
  { n: "258,000",u:"m²", icon: "◈", l: "Jura limestone cladding",  sub: "World's tallest stone-clad tower"  },
  { n: "289",   u: "",   icon: "⬡", l: "Foundation piles",         sub: "1,200mm diameter, 22–27m depth"    },
  { n: "43",    u: "",   icon: "⬆", l: "High-speed elevators",     sub: "3 zones — Low, Mid, High rise"     },
  { n: "351",   u: "m",  icon: "✦", l: "Sky Lounge elevation",     sub: "Highest dining in Kuwait"          },
];

/* ── Tabs ── */
const TABS = [
  {
    id: "form", label: "The Form",
    content: {
      heading: "Born from a single sculptural act.",
      body: [
        "The Al Hamra Tower's geometry was generated by subtracting a spiraling quadrant from a simple prismatic volume — then rotating that removed mass incrementally at each higher level. The result is two hyperbolic paraboloid reinforced-concrete walls — the iconic flared ribbons — extending the full 412 metres of the tower's height.",
        "Architect Mark Sarkisian and the SOM San Francisco team describe it as 'architectural expression through structural form on a grand scale.' The structural system and exterior form evolved together in a process of symbiotic evolution — the structure is the form.",
      ],
      quote: "The building geometry is generated by a spiraling slice subtracted from a simple prismatic volume.",
      credit: "Skidmore, Owings & Merrill LLP — Sculpted High-Rise paper",
      stat: { n: "1st", l: "Asymmetrical skyscraper in the world" },
    },
  },
  {
    id: "facade", label: "The Façade",
    content: {
      heading: "Glass toward the Gulf. Stone toward the desert.",
      body: [
        "Three facades face north, east, and west — fully glazed with insulating low-emissivity glass, maximising views across Kuwait Bay and the Arabian Gulf. No south-facing office exists anywhere in the building.",
        "The south wall is 258,000 m² of Jura limestone — the world's largest area of stone cladding on a single building. Deep angled windows carved into the stone frame oblique views of the city and peninsula while blocking all direct solar radiation.",
      ],
      quote: "The transparent envelope facing north and its solid wall facing south — a response to the environment itself.",
      credit: "SOM Structural Engineering Team",
      stat: { n: "55,000", l: "m² of insulating curtain wall glass" },
    },
  },
  {
    id: "lobby", label: "The Lobby",
    content: {
      heading: "24 metres. No columns. Engineered to be impossible.",
      body: [
        "The main lobby is a 900 m² column-free volume rising 24 metres — made possible by the lamella structure: curved steel columns bent outward from 60 metres above, distributing loads through five interlocking bracing systems (A, B, C, D, E elements) studied via non-linear buckling analysis.",
        "The fiberglass formwork moulds for the lamella were fabricated directly from 3D parametric models — an early example of digital fabrication at supertall scale. The lobby faces north, oriented toward the Arabian Gulf.",
      ],
      quote: "Like an enshrouded figure with its delicate glass veil, the Tower provides spectacular views over much of Kuwait and across the Arabian Gulf.",
      credit: "Al Hamra Firdous Tower Study",
      stat: { n: "900", l: "m² — column-free lobby area" },
    },
  },
  {
    id: "zones", label: "The Zones",
    content: {
      heading: "Three rise zones. Two sky lobbies. One executive crown.",
      body: [
        "The business tower is divided into three stacked zones — Low Rise (Floors 6–26), Mid Rise (31–51), and High Rise (56–73) — each served by dedicated elevator banks. Sky Lobby 1 on Floor 30 and Sky Lobby 2 on Floor 55 provide transfer floors with 7-metre ceilings, full business centres, and employee lounges.",
        "Executive Floors 74–75 represent the highest business address in Kuwait. VIP elevators connect directly from the main lobby to the crown. The Sky Lounge occupies Floors 78–80 at 351 metres — the highest dining experience in Kuwait.",
      ],
      quote: "Executive Floors on the 74th & 75th providing the highest business address in Kuwait with a unique experience.",
      credit: "Al Hamra Tower Technical Specification",
      stat: { n: "74–75", l: "Executive floors — highest address in Kuwait" },
    },
  },
];

export default function TowerOverview() {
  const heroRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const imgY = useSpring(useTransform(scrollYProgress, [0, 1], ["0%", "22%"]), { stiffness: 50, damping: 18 });
  const fade = useTransform(scrollYProgress, [0, 0.7], [1, 0]);

  const [activeTab, setActiveTab] = useState("form");
  const activeContent = TABS.find(t => t.id === activeTab)!.content;

  return (
    <PageLayout>
      {/* ── Hero ──────────────────────────────────────────────────── */}
      <div ref={heroRef} style={{ position: "relative", height: "90vh", minHeight: 520, overflow: "hidden", background: "#0c0b09" }}>
        <motion.img
          src="/assets/tower-render-dusk.jpg"
          alt="Al Hamra Tower — official SOM architectural render at dusk, Kuwait City"
          style={{ y: imgY, position: "absolute", inset: 0, width: "100%", height: "115%",
            objectFit: "cover", objectPosition: "center top" }}
        />
        <div style={{ position: "absolute", inset: 0,
          background: "linear-gradient(to bottom, rgba(12,11,9,0.3) 0%, transparent 30%, rgba(12,11,9,0.25) 65%, rgba(12,11,9,0.9) 100%)" }} />
        <div style={{ position: "absolute", inset: 0,
          background: "linear-gradient(to right, rgba(12,11,9,0.6) 0%, transparent 60%)" }} />
        <motion.div style={{ opacity: fade, position: "absolute", inset: 0, zIndex: 4,
          display: "flex", flexDirection: "column", justifyContent: "flex-end",
          padding: "0 clamp(28px,6vw,96px) clamp(48px,7vh,80px)" }}>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
            style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 20,
              fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL }}>
            <span style={{ width: 32, height: 1, background: `linear-gradient(to right,${PEARL},#D4CFC9)`, flexShrink: 0 }} />
            The Tower · Skidmore, Owings & Merrill · 2006–2011
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.55, duration: 0.9, ease: [0.16,1,0.3,1] }}
            style={{ fontFamily: "Cormorant Garamond,serif", fontStyle: "italic",
              fontWeight: 300, fontSize: "clamp(36px,6vw,88px)", color: "#fff",
              letterSpacing: "-0.02em", lineHeight: 1.0, margin: "0 0 12px" }}>
            The Tower
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.75, duration: 0.8 }}
            style={{ fontFamily: "Jost,sans-serif", fontWeight: 200,
              fontSize: "clamp(13px,1.3vw,18px)", color: "rgba(255,255,255,0.6)",
              maxWidth: 480, lineHeight: 1.7, margin: 0 }}>
            412 metres. First asymmetrical skyscraper in the world.<br />
            World's tallest stone-clad building. Kuwait City, Sharq District.
          </motion.p>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            transition={{ delay: 1.1, duration: 0.6 }}
            style={{ marginTop: 8, fontFamily: "Jost,sans-serif", fontSize: "10px",
              letterSpacing: "0.2em", color: "rgba(255,255,255,0.25)", textTransform: "uppercase" }}>
            © SOM / CTBUH — Architectural render
          </motion.div>
        </motion.div>
      </div>

      {/* ── Stats grid ─────────────────────────────────────────────── */}
      <div style={{ background: "#fff", borderBottom: "1px solid rgba(29,29,27,0.07)" }}>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)" }} className="overview-stats-grid">
          {TOWER_STATS.map(({ n, u, icon, l, sub }, i) => (
            <motion.div key={l}
              initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.6, delay: i * 0.08 }}
              style={{ padding: "clamp(28px,4vh,44px) clamp(20px,3vw,40px)",
                borderRight: [0,1,3,4].includes(i) ? "1px solid rgba(29,29,27,0.07)" : "none",
                borderBottom: i < 3 ? "1px solid rgba(29,29,27,0.07)" : "none",
                display: "flex", flexDirection: "column", gap: 6 }}>
              <div style={{ fontFamily: "Jost,sans-serif", fontSize: "10px",
                color: PEARL, letterSpacing: "0.3em", marginBottom: 4 }}>{icon}</div>
              <div style={{ fontFamily: "Cormorant Garamond,serif",
                fontSize: "clamp(22px,3vw,42px)", fontWeight: 300, color: DARK, lineHeight: 1 }}>
                <CountUp value={n} delay={i * 0.1} />
                {u && <span style={{ fontFamily: "Jost,sans-serif",
                  fontSize: "clamp(11px,1.3vw,17px)", fontWeight: 200, color: PEARL, marginLeft: 4 }}>{u}</span>}
              </div>
              <div style={{ fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
                letterSpacing: "0.2em", textTransform: "uppercase", color: DARK, fontWeight: 400 }}>{l}</div>
              <div style={{ fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.82vw,11px)",
                color: "#767676" }}>{sub}</div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* ── Architecture tabs ──────────────────────────────────────── */}
      <div style={{ background: CREAM, padding: "clamp(60px,9vh,100px) clamp(28px,6vw,96px)" }}>
        {/* Tab bar */}
        <div style={{ display: "flex", gap: 0, borderBottom: "1px solid rgba(29,29,27,0.1)",
          marginBottom: 56, overflowX: "auto" }}>
          {TABS.map(tab => (
            <button key={tab.id} onClick={() => setActiveTab(tab.id)}
              style={{ position: "relative", background: "none", border: "none",
                padding: "14px 28px", cursor: "pointer",
                fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
                letterSpacing: "0.3em", textTransform: "uppercase", whiteSpace: "nowrap",
                color: activeTab === tab.id ? DARK : "#767676",
                fontWeight: activeTab === tab.id ? 500 : 300,
                transition: "color 0.3s" }}>
              {tab.label}
              {activeTab === tab.id && (
                <motion.div layoutId="tab-line"
                  style={{ position: "absolute", bottom: -1, left: 0, right: 0, height: 2,
                    background: `linear-gradient(to right,${PEARL},#D4CFC9)` }} />
              )}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <AnimatePresence mode="wait">
          <motion.div key={activeTab}
            initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -12 }} transition={{ duration: 0.45, ease: "easeOut" }}
            style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "clamp(40px,6vw,100px)" }}
            className="tab-content-grid">
            <div>
              <h2 style={{ fontFamily: "Cormorant Garamond,serif", fontStyle: "italic",
                fontWeight: 300, fontSize: "clamp(24px,3vw,42px)", color: DARK,
                lineHeight: 1.1, marginBottom: 28, letterSpacing: "-0.01em" }}>
                {activeContent.heading}
              </h2>
              {activeContent.body.map((p, i) => (
                <p key={i} style={{ fontFamily: "Jost,sans-serif", fontWeight: 300,
                  fontSize: "clamp(13px,1.05vw,15px)", color: "#5a5a58",
                  lineHeight: 1.9, marginBottom: 16 }}>{p}</p>
              ))}
            </div>
            <div style={{ display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
              <div style={{ borderLeft: `2px solid ${PEARL}`, paddingLeft: 24, marginBottom: 40 }}>
                <p style={{ fontFamily: "Cormorant Garamond,serif", fontStyle: "italic",
                  fontSize: "clamp(15px,1.4vw,19px)", color: DARK, lineHeight: 1.7, margin: "0 0 12px" }}>
                  "{activeContent.quote}"
                </p>
                <div style={{ fontFamily: "Jost,sans-serif", fontSize: "10px",
                  letterSpacing: "0.28em", textTransform: "uppercase", color: PEARL }}>
                  {activeContent.credit}
                </div>
              </div>
              <TiltCard>
                <div style={{ background: STONE, padding: "clamp(24px,3vh,36px) clamp(20px,3vw,36px)" }}>
                  <div style={{ fontFamily: "Cormorant Garamond,serif",
                    fontSize: "clamp(36px,5vw,68px)", fontWeight: 300, color: DARK, lineHeight: 1 }}>
                    {activeContent.stat.n}
                  </div>
                  <div style={{ fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
                    letterSpacing: "0.2em", textTransform: "uppercase", color: "#767676", marginTop: 8 }}>
                    {activeContent.stat.l}
                  </div>
                </div>
              </TiltCard>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>

      {/* ── Awards strip ───────────────────────────────────────────── */}
      <div style={{ background: "#fff", padding: "clamp(48px,7vh,80px) clamp(28px,6vw,96px)",
        borderTop: "1px solid rgba(29,29,27,0.07)" }}>
        <div style={{ fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
          letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL, marginBottom: 36 }}>
          Awards & Recognition
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(240px,1fr))", gap: 24 }}>
          {[
            { year: "2007", title: "Miami Architectural Biennial", sub: "Bronze — Under Construction Category" },
            { year: "2010", title: "Cityscape Award", sub: "Commercial Mixed-use Developments" },
            { year: "2011", title: "Time Magazine", sub: "Best Inventions of the Year" },
            { year: "2012", title: "CTBUH Award", sub: "Best Tall Building Middle East" },
            { year: "2013", title: "MIPIM Architectural Review", sub: "Future Project Award" },
            { year: "2014", title: "Emirates Glass LEAF Award", sub: "International Award" },
            { year: "2016", title: "MEA Awards", sub: "Sustainable Design Recognition" },
            { year: "2019", title: "World Architecture Festival", sub: "Completed Buildings" },
          ].map(({ year, title, sub }, i) => (
            <motion.div key={year + title}
              initial={{ opacity: 0, x: -12 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.6, delay: i * 0.06 }}
              style={{ borderLeft: `1px solid rgba(200,185,154,0.4)`, paddingLeft: 20 }}>
              <div style={{ fontFamily: "Cormorant Garamond,serif",
                fontSize: "clamp(20px,2vw,28px)", fontWeight: 300, color: DARK, lineHeight: 1, marginBottom: 6 }}>
                {year}
              </div>
              <div style={{ fontFamily: "Jost,sans-serif", fontSize: "clamp(11px,0.9vw,13px)",
                fontWeight: 400, color: DARK, marginBottom: 4 }}>{title}</div>
              <div style={{ fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.8vw,11px)",
                color: "#767676" }}>{sub}</div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* ── CTA ────────────────────────────────────────────────────── */}
      <div style={{ background: DARK, padding: "clamp(60px,9vh,100px) clamp(28px,6vw,96px)",
        textAlign: "center" }}>
        <div style={{ fontFamily: "Cormorant Garamond,serif", fontStyle: "italic",
          fontWeight: 300, fontSize: "clamp(28px,4vw,56px)", color: "#fff",
          letterSpacing: "-0.01em", marginBottom: 40 }}>
          Every office. Every view. The Gulf.
        </div>
        <div style={{ display: "flex", justifyContent: "center", gap: 24, flexWrap: "wrap" }}>
          <Link to="/tower/design" style={{ display: "inline-flex", alignItems: "center", gap: 12,
            background: "none", border: `1px solid rgba(200,185,154,0.4)`, color: PEARL,
            fontFamily: "Jost,sans-serif", fontSize: "10.5px", letterSpacing: "0.25em",
            textTransform: "uppercase", padding: "15px 32px", textDecoration: "none",
            transition: "all 0.3s" }}
            onMouseEnter={e=>{e.currentTarget.style.borderColor=PEARL;e.currentTarget.style.color="#fff";}}
            onMouseLeave={e=>{e.currentTarget.style.borderColor="rgba(200,185,154,0.4)";e.currentTarget.style.color=PEARL;}}>
            Design & Engineering
          </Link>
          <Link to="/leasing/inquiry#inquiry-form" style={{ display: "inline-flex", alignItems: "center", gap: 12,
            background: "#fff", color: DARK, fontFamily: "Jost,sans-serif",
            fontSize: "10.5px", letterSpacing: "0.25em", textTransform: "uppercase",
            padding: "15px 32px", textDecoration: "none", transition: "all 0.3s" }}
            onMouseEnter={e=>{e.currentTarget.style.background=PEARL;e.currentTarget.style.color="#fff";}}
            onMouseLeave={e=>{e.currentTarget.style.background="#fff";e.currentTarget.style.color=DARK;}}>
            Enquire by appointment
          </Link>
        </div>
      </div>

      <style>{`
        .overview-stats-grid { grid-template-columns: repeat(3,1fr) !important; }
        .tab-content-grid { grid-template-columns: 1fr 1fr !important; }
        @media (max-width: 900px) {
          .overview-stats-grid { grid-template-columns: 1fr 1fr !important; }
          .tab-content-grid { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 560px) {
          .overview-stats-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </PageLayout>
  );
}
