import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { PageLayout }  from "@/components/layout/PageLayout";
import { PageHero }    from "@/components/shared/PageHero";
import { useI18n }     from "@/lib/i18n";

const PEARL  = "#C8B99A";
const DARK   = "#1D1D1B";

const FONT = "'Century Gothic','AppleGothic','Gill Sans MT','Gill Sans',Futura,'Trebuchet MS',sans-serif";

/* ── Bilingual content dictionary ─────────────────────────────────────
   Arabic copy sourced from V01 translation sheet (The Tower).
──────────────────────────────────────────────────────────────────────── */
const CONTENT = {
  en: {
    heroTitle: "Design & Engineering",
    heroSubtitle:
      "How a single formal act — subtracting a spiraling quadrant from a prismatic volume — created both the architectural identity and the structural system of Kuwait's most ambitious building.",
    crumbHome: "Home",
    crumbTower: "The Tower",

    facadeKicker: "The Dual Façade",
    facadeHeadingLine1: "Glass toward the Gulf.",
    facadeHeadingLine2: "Stone toward the desert.",
    facadeP1Part1:
      "Three facades face north, east, and west — fully glazed with insulating low-emissivity glass, maximising views across Kuwait Bay and the Arabian Gulf.",
    facadeP1Strong: " Not a single office in the building faces south.",
    facadeP2:
      "The south wall is 258,000 m² of Jura limestone — the world's largest area of stone cladding on any single building. Deep angled windows carved into the stone frame oblique city and peninsula views while completely blocking direct solar radiation.",
    facadeStats: [
      { n: "258,000", u: "m²", l: "World record limestone cladding" },
      { n: "55,000",  u: "m²", l: "Low-E curtain wall glass" },
      { n: "0",       u: "",   l: "South-facing offices" },
    ],

    lamellaKicker: "The Lamella Structure",
    lamellaHeadingLine1: "24 metres. No columns.",
    lamellaHeadingLine2: "Engineered to be impossible.",
    lamellaP1:
      "The main lobby rises 24 metres without a single column — achieved through the lamella bracing system. The north tower columns, vertical from Level 12 upward, slope outward following a circular arch from 60 metres high, intercepting the ground slab 7.6 metres further north than a vertical column would.",
    lamellaP2:
      "Five interlocking element types — A, B, C, D, E — form a three-dimensional web. Non-linear buckling analysis confirmed the system: adding the D elements alone increased buckling resistance by a factor of two. All fiberglass formwork moulds were fabricated directly from parametric 3D models — an early milestone in computational construction.",
    lamellaQuote:
      "\"The geometry of this area is generated by the application of the principles of the laminar structure supporting the tower above and below articulates space.\"",
    lamellaQuoteCredit: "SOM / Skidmore, Owings & Merrill",

    lobbyCaption1: "Escalator Hall · Steel Sculpture",
    lobbyCaption2: "Trencadis Façade · Upper Floors",

    specKicker: "Technical Specification",
    specHeading: "The numbers behind the form.",

    drawingsKicker: "Drawings & Documentation",
    drawingsPlanLabel: "SOM — Typical office floor plan",
    drawingsPlanNote: "~2,300 m² net leasable area per floor",
    drawingsElevKicker: "Elevation Drawings",
    drawingsLabelSouth: "South wall elevation · 412.6 m",
    drawingsLabelContext: "South elevation — full context",

    specs: [
      { cat: "Height", rows: [
        ["Height to tip",        "412.6 m"],
        ["Occupied height",      "371.4 m"],
        ["Top floor height",     "368 m"],
        ["Sky Lounge elevation", "351 m"],
      ]},
      { cat: "Structure", rows: [
        ["Structural type",       "RC shear wall core + perimeter MRF"],
        ["Foundation",            "289 piles × 1,200mm dia."],
        ["Pile depth range",      "22–27 m"],
        ["Raft thickness",        "4.0 m"],
        ["Structural steel",      "6,000 tons"],
        ["Reinforcing steel",     "38,000 tons"],
        ["Concrete poured",       "195,000 m³ / 500,000 tons"],
        ["Core wall thickness",   "300 mm – 1,200 mm"],
      ]},
      { cat: "Facade", rows: [
        ["South wall limestone",  "258,000 m² (world record)"],
        ["Curtain wall glass",    "55,000 m²"],
        ["Glass type",            "Insulated low-emissivity coating"],
        ["Curved glass units",    "~30% of total glass area"],
        ["Stone type (lower)",    "Jura limestone tiles"],
        ["Stone type (upper)",    "Trencadis (mesh + crushed limestone)"],
      ]},
      { cat: "Floors", rows: [
        ["Total levels",          "80"],
        ["Office floors",         "62"],
        ["Office floor BUA",      "2,300 m² per floor"],
        ["Tenantable range",      "450 m² – 1,750 m²"],
        ["South-facing offices",  "Zero — none"],
        ["Sky Lobby 1",           "Floor 30 (7m ceiling)"],
        ["Sky Lobby 2",           "Floor 55 (7m ceiling)"],
        ["Executive floors",      "74–75"],
        ["Sky Lounge",            "Floors 78–80"],
      ]},
      { cat: "Services", rows: [
        ["Elevators (tower)",     "43"],
        ["Escalators",            "16"],
        ["Elevator zones",        "3 — Low / Mid / High rise"],
        ["VIP elevator",          "Direct lobby → crown"],
        ["Power supply",          "100% redundancy"],
        ["Electrical substations","5 (Floors B2, 4, 27, 52, 76)"],
        ["IT backbone",           "Fibre optic smart building"],
      ]},
      { cat: "Engineering Team", rows: [
        ["Architect",             "Skidmore, Owings & Merrill LLP"],
        ["Structural engineer",   "SOM San Francisco"],
        ["MEP engineer",          "SOM Chicago"],
        ["Local architect",       "Al Jazera Consultants, Kuwait"],
        ["Wind engineer",         "BMT Fluid Mechanics, London"],
        ["Geotechnical engineer", "Consultancy Group Company, Beirut"],
        ["Client",                "Ajial Real Estate & Entertainment Co."],
        ["Contractor",            "Ahmadiah Contracting & Trading Co."],
        ["Design code",           "IBC 2003 + ACI 318-02M"],
        ["Construction",          "2006–2011"],
      ]},
    ],
  },
  ar: {
    heroTitle: "التصميم والهندسة",
    heroSubtitle:
      "كيف حقّق إجراءٌ تكويني واحد — اقتطاع رُبعٍ حلزونيّ من حجمٍ موشوريّ — هويةَ العمارة والمنظومةَ الإنشائيةَ معاً لأكثر مبانٍ الكويت طموحاً.",
    crumbHome: "الرئيسية",
    crumbTower: "البرج",

    facadeKicker: "الواجهة المزدوجة",
    facadeHeadingLine1: "الزجاجُ نحو الخليج.",
    facadeHeadingLine2: "والحَجَرُ نحو الصحراء.",
    facadeP1Part1:
      "ثلاثُ واجهاتٍ تواجه الشمال والشرق والغرب — مكسوّةٌ بالكامل بزجاجٍ عازلٍ منخفض الانبعاثية، تُعظّم المشاهد عبر جون الكويت والخليج العربي.",
    facadeP1Strong: " لا يطلّ أيّ مكتب من مكاتب البرج جنوباً.",
    facadeP2:
      "الجدارُ الجنوبيّ هو 258,000م² من حجر الجوراسيك الجيري — أكبرُ مساحة كسوة حجرية على أيّ مبنى منفرد في العالم. نوافذُ مائلةٌ عميقةٌ منحوتةٌ في الحجر تُؤطّر مشاهدَ مائلةً للمدينة وشبه الجزيرة، فيما تحجبُ الإشعاع الشمسيّ المباشر تماماً.",
    facadeStats: [
      { n: "258,000", u: "م²", l: "رقمٌ عالميّ في الكسوة الحجرية" },
      { n: "55,000",  u: "م²", l: "زجاجُ الجدار الستائريّ منخفض الانبعاثية" },
      { n: "0",       u: "",   l: "مكاتبُ تطلّ جنوباً" },
    ],

    lamellaKicker: "منظومة اللاميلا",
    lamellaHeadingLine1: "24 متراً. بلا أعمدة.",
    lamellaHeadingLine2: "هندسةٌ تتحدّى المُستحيل.",
    lamellaP1:
      "ترتفعُ الردهةُ الرئيسةُ 24 متراً دون عمودٍ واحد — بفضل منظومة التدعيم باللاميلا. أعمدةُ البرج الشماليّ، العموديةُ ابتداءً من الطابق 12، تنحرفُ خارجياً متّبعةً قوساً دائرياً من ارتفاع 60 متراً، لتلتقي مع البلاطة الأرضية على بُعد 7.6 متراً شمالاً أبعدَ مما لو كانت عمودية.",
    lamellaP2:
      "خمسةُ أنواعٍ من العناصر المتشابكة — A، B، C، D، E — تُكوّنُ شبكةً ثلاثيةَ الأبعاد. أكّد تحليلُ الانبعاج اللاخطيّ كفاءةَ النظام: إضافةُ عناصر D وحدها رفعت مقاومةَ الانبعاج بمعاملٍ مقدارُه اثنان. صُنعت كلُّ قوالب الفايبرغلاس المؤقتة مباشرةً من نماذجَ بارامتريةٍ ثلاثية الأبعاد — معلمٌ مبكّرٌ في البناء الحاسوبيّ.",
    lamellaQuote:
      "«تتولّد هندسةُ هذه المنطقة من تطبيق مبادئ المنظومة اللاميلية الداعمة للبرج فوقها وأسفلها، فتُشكّلُ الفضاءَ وتُمَفصِله.»",
    lamellaQuoteCredit: "سكيدمور وأوينغز وميريل (SOM)",

    lobbyCaption1: "قاعةُ السلالم الكهربائية · منحوتةٌ فولاذية",
    lobbyCaption2: "واجهةُ الترِنكاديس · الطوابق العُليا",

    specKicker: "المواصفات الفنية",
    specHeading: "الأرقامُ خلف التكوين.",

    drawingsKicker: "المخططات والوثائق",
    drawingsPlanLabel: "SOM — مخطّط الطابق المكتبيّ النموذجيّ",
    drawingsPlanNote: "نحو 2,300م² من المساحة الصافية القابلة للتأجير لكلّ طابق",
    drawingsElevKicker: "مخطّطات الواجهات",
    drawingsLabelSouth: "واجهةُ الجدار الجنوبيّ · 412.6 م",
    drawingsLabelContext: "الواجهةُ الجنوبية — السياقُ الكامل",

    specs: [
      { cat: "الارتفاع", rows: [
        ["الارتفاع حتى القمة",     "412.6 م"],
        ["الارتفاع المشغول",        "371.4 م"],
        ["ارتفاع الطابق العُلويّ", "368 م"],
        ["ارتفاع صالة السماء",     "351 م"],
      ]},
      { cat: "البنية الإنشائية", rows: [
        ["النوع الإنشائيّ",         "نواةٌ خرسانيةٌ بجدرانِ قصٍّ + إطارٌ محيطيّ مقاومٌ للعزوم"],
        ["الأساسات",                "289 ركيزةً بقطر 1,200مم"],
        ["مدى عُمق الركائز",         "22–27 م"],
        ["سُمك اللُّبادة",           "4.0 م"],
        ["الفولاذ الإنشائيّ",        "6,000 طن"],
        ["فولاذ التسليح",            "38,000 طن"],
        ["الخرسانة المصبوبة",        "195,000 م³ / 500,000 طن"],
        ["سُمك جدار النواة",         "300 مم – 1,200 مم"],
      ]},
      { cat: "الواجهة", rows: [
        ["كسوة الجدار الجنوبيّ",     "258,000 م² (رقمٌ عالميّ)"],
        ["زجاجُ الجدار الستائريّ",   "55,000 م²"],
        ["نوع الزجاج",               "عازلٌ بطلاءٍ منخفض الانبعاثية"],
        ["وحدات الزجاج المنحني",     "نحو 30٪ من إجمالي الزجاج"],
        ["نوع الحجر (السُّفلى)",      "بلاطُ حجر الجوراسيك"],
        ["نوع الحجر (العُلوية)",      "ترِنكاديس (شبكٌ + حجرٌ مكسّر)"],
      ]},
      { cat: "الطوابق", rows: [
        ["إجمالي المستويات",         "80"],
        ["طوابق المكاتب",            "62"],
        ["مساحةُ الطابق المبنيّة",   "2,300 م² للطابق"],
        ["نطاقُ الإيجار",             "450 م² – 1,750 م²"],
        ["مكاتبُ جنوبية",             "صفر — لا توجد"],
        ["ردهةُ سماءٍ 1",             "الطابق 30 (سقف 7م)"],
        ["ردهةُ سماءٍ 2",             "الطابق 55 (سقف 7م)"],
        ["الطوابق التنفيذية",         "74–75"],
        ["صالةُ السماء",              "الطوابق 78–80"],
      ]},
      { cat: "الخدمات", rows: [
        ["المصاعد (البرج)",          "43"],
        ["السلالم الكهربائية",        "16"],
        ["مناطقُ المصاعد",            "3 — المنخفضة / الوسطى / العالية"],
        ["مصعدٌ كبار الشخصيات",       "من الردهة إلى التاج مباشرةً"],
        ["إمدادُ الطاقة",              "تكرارٌ 100٪"],
        ["محطّات التحويل الكهربائية", "5 (الطوابق B2 و4 و27 و52 و76)"],
        ["العمودُ الفِقَريّ للاتصالات", "ألياف ضوئية — مبنى ذكيّ"],
      ]},
      { cat: "الفريق الهندسيّ", rows: [
        ["المهندس المعماريّ",        "سكيدمور وأوينغز وميريل LLP"],
        ["المهندس الإنشائيّ",         "SOM سان فرانسيسكو"],
        ["مهندس الكهروميكانيكا",      "SOM شيكاغو"],
        ["المعماري المحلّي",          "استشاريّو الجزيرة، الكويت"],
        ["مهندس الرياح",              "BMT لميكانيكا الموائع، لندن"],
        ["مهندس الجيوتقنية",          "شركة كونسلتنسي غروب، بيروت"],
        ["العميل",                    "شركة أجيال العقارية والترفيهية"],
        ["المقاول",                   "شركة الأحمدية للمقاولات والتجارة"],
        ["كودُ التصميم",               "IBC 2003 + ACI 318-02M"],
        ["البناء",                    "2006–2011"],
      ]},
    ],
  },
} as const;

interface SpecTableProps { cat: string; rows: readonly (readonly [string, string])[]; }
function SpecTable({ cat, rows }: SpecTableProps) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  return (
    <div ref={ref} style={{ marginBottom: 40 }}>
      <div style={{ fontFamily: FONT, fontSize: "10px",
        letterSpacing: "0.4em", textTransform: "uppercase", color: PEARL,
        marginBottom: 16, paddingBottom: 12,
        borderBottom: `1px solid rgba(200,185,154,0.25)` }}>{cat}</div>
      {rows.map(([label, value], i) => (
        <motion.div key={label}
          initial={{ opacity: 0, x: -10 }}
          animate={inView ? { opacity: 1, x: 0 } : {}}
          transition={{ duration: 0.5, delay: i * 0.04 }}
          style={{ display: "flex", gap: 16,
            padding: "11px 0", borderBottom: i < rows.length-1 ? "1px solid rgba(29,29,27,0.06)" : "none" }}>
          <div style={{ fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
            color: "#6B6B6B", minWidth: 200, flexShrink: 0, letterSpacing: "0.05em" }}>{label}</div>
          <div style={{ fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
            color: DARK, fontWeight: 400 }}>{value}</div>
        </motion.div>
      ))}
    </div>
  );
}

export default function TowerDesign() {
  const { lang } = useI18n();
  const c = CONTENT[lang];
  const facadeRef = useRef<HTMLDivElement>(null);
  const facadeInView = useInView(facadeRef, { once: true, margin: "-80px" });

  return (
    <PageLayout>
      <PageHero
        title={c.heroTitle}
        subtitle={c.heroSubtitle}
        image="/assets/tower-facade-up.jpg"
        crumbs={[{ label: c.crumbHome, href: "/" }, { label: c.crumbTower, href: "/tower" }]}
      />

      {/* ── The Dual Facade ─────────────────────────────────────── */}
      <div style={{ background: "#fff" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", minHeight: "60vh" }}
          className="design-grid-1">
          <div style={{ position: "relative", overflow: "hidden", background: "#0c0b09", minHeight: 360 }}>
            <img
              loading="lazy" src="/assets/facade-dual-glass-stone.jpg"
              alt={lang === "ar" ? "برج الحمراء — واجهةٌ مزدوجة: جدارٌ ستائريّ زجاجيّ وحجرُ الجوراسيك جنباً إلى جنب" : "Al Hamra Tower dual facade — glass curtain wall and Jura limestone side by side"}
              style={{ width: "100%", height: "100%", objectFit: "cover",
                objectPosition: "center", display: "block" }} />
          </div>
          <div ref={facadeRef}
            style={{ padding: "clamp(48px,8vh,96px) clamp(32px,5vw,80px)",
              display: "flex", flexDirection: "column", justifyContent: "center" }}>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={facadeInView ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.8, ease: [0.16,1,0.3,1] }}>
              <div style={{ fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
                letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL, marginBottom: 20 }}>
                {c.facadeKicker}
              </div>
              <h2 style={{ fontFamily: FONT,
                fontWeight: 300, fontSize: "clamp(26px,3.5vw,48px)",
                color: DARK, lineHeight: 1.1, letterSpacing: "-0.01em", marginBottom: 24 }}>
                {c.facadeHeadingLine1}<br />{c.facadeHeadingLine2}
              </h2>
              <p style={{ fontFamily: FONT, fontWeight: 300,
                fontSize: "clamp(13px,1.05vw,15px)", color: "#5a5a58",
                lineHeight: 1.9, marginBottom: 20 }}>
                {c.facadeP1Part1}
                <strong style={{ color: DARK, fontWeight: 400 }}>{c.facadeP1Strong}</strong>
              </p>
              <p style={{ fontFamily: FONT, fontWeight: 300,
                fontSize: "clamp(13px,1.05vw,15px)", color: "#5a5a58", lineHeight: 1.9, marginBottom: 32 }}>
                {c.facadeP2}
              </p>
              <div style={{ display: "flex", gap: 40, flexWrap: "wrap" }}>
                {c.facadeStats.map(({ n, u, l }) => (
                  <div key={l}>
                    <div style={{ fontFamily: FONT,
                      fontSize: "clamp(24px,3vw,38px)", fontWeight: 300, color: DARK, lineHeight: 1 }}>
                      {n}{u && <span style={{ fontFamily: FONT,
                        fontSize: "0.4em", color: PEARL, marginLeft: 3, fontWeight: 200 }}>{u}</span>}
                    </div>
                    <div style={{ fontFamily: FONT, fontSize: "10px",
                      letterSpacing: "0.2em", textTransform: "uppercase",
                      color: "#6B6B6B", marginTop: 6 }}>{l}</div>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      {/* ── The Lamella Lobby ───────────────────────────────────── */}
      <div style={{ background: "#FAFAFA", padding: "clamp(60px,9vh,100px) clamp(28px,6vw,96px)" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "clamp(48px,6vw,100px)" }}
          className="design-grid-2">
          <div>
            <div style={{ fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL, marginBottom: 20 }}>
              {c.lamellaKicker}
            </div>
            <h2 style={{ fontFamily: FONT,
              fontWeight: 300, fontSize: "clamp(24px,3.2vw,44px)",
              color: DARK, lineHeight: 1.1, marginBottom: 24 }}>
              {c.lamellaHeadingLine1}<br />{c.lamellaHeadingLine2}
            </h2>
            <p style={{ fontFamily: FONT, fontWeight: 300,
              fontSize: "clamp(13px,1.05vw,15px)", color: "#5a5a58",
              lineHeight: 1.9, marginBottom: 16 }}>
              {c.lamellaP1}
            </p>
            <p style={{ fontFamily: FONT, fontWeight: 300,
              fontSize: "clamp(13px,1.05vw,15px)", color: "#5a5a58",
              lineHeight: 1.9, marginBottom: 28 }}>
              {c.lamellaP2}
            </p>
            <div style={{ borderLeft: lang === "ar" ? "none" : `2px solid ${PEARL}`,
              borderRight: lang === "ar" ? `2px solid ${PEARL}` : "none",
              paddingLeft: lang === "ar" ? 0 : 20,
              paddingRight: lang === "ar" ? 20 : 0 }}>
              <p style={{ fontFamily: FONT, fontStyle: "italic",
                fontSize: "clamp(14px,1.3vw,18px)", color: DARK, lineHeight: 1.7, margin: 0 }}>
                {c.lamellaQuote}
              </p>
              <div style={{ fontFamily: FONT, fontSize: "10px",
                letterSpacing: "0.28em", textTransform: "uppercase", color: PEARL, marginTop: 10 }}>
                {c.lamellaQuoteCredit}
              </div>
            </div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 4, position: "relative", minHeight: 480 }}>
            <div style={{ position: "relative", overflow: "hidden", flex: 2 }}>
              <img
              loading="lazy" src="/assets/lobby-grand-lamella.jpg"
                alt={lang === "ar" ? "ردهةُ برج الحمراء — أقواسُ اللاميلا البيضاء، فضاءٌ بلا أعمدة بارتفاع 24م" : "Al Hamra Tower lobby — white lamella arches, 24m column-free atrium"}
                style={{ width: "100%", height: "100%", objectFit: "cover", minHeight: 360,
                  objectPosition: "center", display: "block" }} />
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 4 }}>
              <div style={{ position: "relative", overflow: "hidden", height: 160 }}>
                <img
              loading="lazy" src="/assets/lobby-escalator-art.jpg"
                  alt={lang === "ar" ? "سلالمُ الحمراء الكهربائية ومنحوتةُ السقف الفولاذية" : "Al Hamra escalator and sculptural steel ceiling installation"}
                  style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "center", display: "block" }} />
                <div style={{ position: "absolute", bottom: 8, left: 10, fontFamily: FONT, fontSize: "9px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(255,255,255,0.55)" }}>{c.lobbyCaption1}</div>
              </div>
              <div style={{ position: "relative", overflow: "hidden", height: 160 }}>
                <img
              loading="lazy" src="/assets/facade-trencadis-detail.jpg"
                  alt={lang === "ar" ? "واجهةُ برج الحمراء — تفصيلُ الحجر الجيريّ والترِنكاديس" : "Al Hamra Tower facade — limestone and trencadis mosaic detail"}
                  style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "center", display: "block" }} />
                <div style={{ position: "absolute", bottom: 8, left: 10, fontFamily: FONT, fontSize: "9px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(200,185,154,0.8)" }}>{c.lobbyCaption2}</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Full Specification Table ────────────────────────────── */}
      <div style={{ background: "#fff", padding: "clamp(60px,9vh,100px) clamp(28px,6vw,96px)" }}>
        <div style={{ marginBottom: 56 }}>
          <div style={{ fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
            letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL, marginBottom: 16 }}>
            {c.specKicker}
          </div>
          <h2 style={{ fontFamily: FONT,
            fontWeight: 300, fontSize: "clamp(26px,3.5vw,48px)",
            color: DARK, lineHeight: 1.1 }}>
            {c.specHeading}
          </h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "clamp(32px,5vw,80px)" }}
          className="spec-table-grid">
          <div>
            {c.specs.slice(0,3).map(s => <SpecTable key={s.cat} cat={s.cat} rows={s.rows as readonly (readonly [string, string])[]} />)}
          </div>
          <div>
            {c.specs.slice(3).map(s => <SpecTable key={s.cat} cat={s.cat} rows={s.rows as readonly (readonly [string, string])[]} />)}
          </div>
        </div>
      </div>

      {/* ── Drawings & Documentation ─────────────────────────────── */}
      <div style={{ background: "#FAFAFA", padding: "clamp(48px,7vh,80px) clamp(28px,6vw,96px)" }}>

        <div style={{ fontFamily: FONT,
          fontSize: "clamp(10px,0.85vw,11px)", letterSpacing: "0.45em",
          textTransform: "uppercase", color: PEARL, marginBottom: 48 }}>
          {c.drawingsKicker}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }} transition={{ duration: 0.8 }}
          style={{ marginBottom: 64 }}
        >
          <img
            src="/assets/drawings/floor-plan-typical.jpg"
            alt={lang === "ar" ? "SOM — مخطّط طابق المكاتب النموذجيّ لبرج الحمراء، نحو 2,300م² صافي" : "SOM — Al Hamra Tower typical office floor plan, ~2,300 m² NLA per floor"}
            loading="lazy"
            style={{ width: "100%", display: "block", border: "1px solid rgba(29,29,27,0.07)" }}
          />
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline",
            marginTop: 14, flexWrap: "wrap", gap: 8 }}>
            <div style={{ fontFamily: FONT,
              fontSize: "10px", letterSpacing: "0.22em", textTransform: "uppercase", color: "#6B6B6B" }}>
              {c.drawingsPlanLabel}
            </div>
            <div style={{ fontFamily: FONT,
              fontSize: "10px", letterSpacing: "0.18em", textTransform: "uppercase", color: PEARL }}>
              {c.drawingsPlanNote}
            </div>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }} transition={{ duration: 0.8, delay: 0.15 }}
        >
          <div style={{ fontFamily: FONT,
            fontSize: "10px", letterSpacing: "0.3em", textTransform: "uppercase",
            color: "#6B6B6B", marginBottom: 20 }}>
            {c.drawingsElevKicker}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 32 }}
            className="elevation-grid">
            {[
              { src: "/assets/drawings/south-wall-elevation.jpg", label: c.drawingsLabelSouth },
              { src: "/assets/drawings/massing-05-elevation.jpg", label: c.drawingsLabelContext },
            ].map(({ src, label }) => (
              <div key={label}>
                <img src={src} alt={label} loading="lazy"
                  style={{ width: "100%", display: "block", border: "1px solid rgba(29,29,27,0.07)" }} />
                <div style={{ fontFamily: FONT,
                  fontSize: "10px", letterSpacing: "0.2em", textTransform: "uppercase",
                  color: "#6B6B6B", marginTop: 12 }}>{label}</div>
              </div>
            ))}
          </div>
        </motion.div>
      </div>

      <style>{`
        .design-grid-1, .design-grid-2 { grid-template-columns: 1fr 1fr !important; }
        .spec-table-grid { grid-template-columns: 1fr 1fr !important; }
        .design-drawing-grid { grid-template-columns: 1fr 1fr !important; }
        .elevation-grid { grid-template-columns: 1fr 1fr !important; }

        .massing-scroll {
          display: flex;
          gap: 20px;
          overflow-x: auto;
          padding-bottom: 8px;
          scroll-snap-type: x mandatory;
          -webkit-overflow-scrolling: touch;
        }
        .massing-scroll::-webkit-scrollbar { height: 2px; }
        .massing-scroll::-webkit-scrollbar-track { background: rgba(29,29,27,0.05); }
        .massing-scroll::-webkit-scrollbar-thumb { background: rgba(200,185,154,0.5); border-radius: 1px; }
        .massing-item {
          flex: 0 0 auto;
          height: 340px;
          overflow: hidden;
          scroll-snap-align: start;
        }
        .massing-item img { object-fit: contain; }

        @media (max-width: 768px) {
          .design-grid-1, .design-grid-2 { grid-template-columns: 1fr !important; }
          .spec-table-grid { grid-template-columns: 1fr !important; }
          .design-drawing-grid { grid-template-columns: 1fr !important; }
          .elevation-grid { grid-template-columns: 1fr !important; }
          .massing-item { height: 240px; }
        }
      `}</style>
    </PageLayout>
  );
}
