import { useRef } from "react";
import { motion, useScroll, useTransform, useInView } from "framer-motion";

/* ── Architecture Section ─────────────────────────────────────────────
   Redesigned with PDF content: the architectural story of the form —
   how the building geometry responds to Kuwait's environment,
   the Gulf, the desert sun, and the city.
──────────────────────────────────────────────────────────────────────── */

const PEARL = "#C8B99A";
const GULF  = "#2A5F7A";
const DARK  = "#1D1D1B";

const SPECS = [
  { n: "258,000",  u: "m²",  l: "Jura limestone cladding — world record" },
  { n: "195,000",  u: "m³",  l: "Reinforced concrete poured"             },
  { n: "289",      u: "",    l: "Foundation piles, 1.2m diameter"         },
  { n: "55,000",   u: "m²",  l: "Curtain wall glass panels"              },
];

export function Architecture() {
  const ref    = useRef<HTMLElement>(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });

  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const imgY = useTransform(scrollYProgress, [0, 1], ["0%", "12%"]);

  return (
    <section ref={ref} style={{ background: "#fff", overflow: "hidden" }}>

      {/* ── Row 1: Full story + render ─────────────────────────────── */}
      <div style={{
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        minHeight: "70vh",
      }} className="arch-grid-1">

        {/* Left — SOM render, dusk purple sky */}
        <motion.div
          style={{ position: "relative", overflow: "hidden", background: "#0c0b09" }}
        >
          <motion.img
            src="/assets/tower-render-dusk.jpg"
            alt="Al Hamra Tower — SOM architectural render at dusk, Kuwait City"
            style={{ y: imgY, width: "100%", height: "115%",
              objectFit: "cover", objectPosition: "center top", display: "block" }}
          />
          {/* Pearl overlay bottom */}
          <div style={{
            position: "absolute", bottom: 0, left: 0, right: 0, height: "40%",
            background: "linear-gradient(to top, rgba(12,11,9,0.7), transparent)",
            pointerEvents: "none",
          }} />
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ delay: 0.8, duration: 0.8 }}
            style={{
              position: "absolute", bottom: 24, left: 24, right: 24, zIndex: 2,
              fontFamily: "Jost,sans-serif", fontSize: "10px",
              letterSpacing: "0.3em", textTransform: "uppercase",
              color: "rgba(255,255,255,0.4)",
            }}
          >
            © SOM / CTBUH — Architectural render
          </motion.div>
        </motion.div>

        {/* Right — The Form Story */}
        <div style={{
          padding: "clamp(48px,8vh,100px) clamp(32px,5vw,80px)",
          display: "flex", flexDirection: "column", justifyContent: "center",
        }}>
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={inView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.8, ease: [0.16,1,0.3,1] }}
          >
            {/* Kicker */}
            <div style={{
              display: "flex", alignItems: "center", gap: 14, marginBottom: 28,
              fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL,
            }}>
              <span style={{ width: 32, height: 1,
                background: `linear-gradient(to right, ${PEARL}, #D4CFC9)`, flexShrink: 0 }} />
              SOM Architecture · 2006–2011
            </div>

            <h2 style={{
              fontFamily: "Cormorant Garamond,serif", fontStyle: "italic",
              fontWeight: 300, fontSize: "clamp(28px,3.8vw,52px)",
              color: DARK, lineHeight: 1.1, letterSpacing: "-0.01em", marginBottom: 24,
            }}>
              A form born from<br />sun, wind, and the Gulf.
            </h2>

            <p style={{
              fontFamily: "Jost,sans-serif", fontWeight: 300,
              fontSize: "clamp(13px,1.1vw,15px)", color: "#5a5a58",
              lineHeight: 1.9, marginBottom: 20,
            }}>
              The Al Hamra Tower's geometry was generated by a single decisive act: 
              subtracting a spiraling quadrant from a simple prismatic volume, 
              then rotating it incrementally at each higher level. The result is 
              two hyperbolic paraboloid walls — the iconic flared ribbons — that 
              extend the full 412 metres of the building's height.
            </p>
            <p style={{
              fontFamily: "Jost,sans-serif", fontWeight: 300,
              fontSize: "clamp(13px,1.1vw,15px)", color: "#5a5a58",
              lineHeight: 1.9, marginBottom: 36,
            }}>
              The transparent glass envelope faces north, west, and east — toward 
              the Arabian Gulf. The monolithic stone wall faces south — shielding 
              every office from Kuwait's desert sun. Architecture and engineering 
              evolved together. The structure <em>is</em> the form.
            </p>

            {/* Quote from SOM paper */}
            <div style={{
              borderLeft: `2px solid ${PEARL}`,
              paddingLeft: 20, marginBottom: 36,
            }}>
              <p style={{
                fontFamily: "Cormorant Garamond,serif", fontStyle: "italic",
                fontSize: "clamp(15px,1.4vw,18px)", color: DARK,
                lineHeight: 1.7, margin: 0,
              }}>
                "Like an enshrouded figure with its delicate glass veil, the Tower 
                provides spectacular views over much of Kuwait and across the Arabian Gulf."
              </p>
              <div style={{
                fontFamily: "Jost,sans-serif", fontSize: "10px",
                letterSpacing: "0.3em", textTransform: "uppercase",
                color: PEARL, marginTop: 12,
              }}>
                Skidmore, Owings & Merrill LLP
              </div>
            </div>

            {/* Awards */}
            <div style={{
              display: "flex", flexWrap: "wrap", gap: "8px 16px",
            }}>
              {[
                "Cityscape Award 2010",
                "Chicago Athenaeum",
                "MIPIM Architectural Review",
                "Miami Architectural Biennial 2007",
              ].map(award => (
                <span key={award} style={{
                  fontFamily: "Jost,sans-serif", fontSize: "10px",
                  letterSpacing: "0.2em", textTransform: "uppercase",
                  color: GULF, padding: "4px 12px",
                  border: `1px solid rgba(42,95,122,0.3)`,
                }}>
                  {award}
                </span>
              ))}
            </div>
          </motion.div>
        </div>
      </div>

      {/* ── Row 2: Material specs strip ────────────────────────────── */}
      <div style={{
        borderTop: "1px solid rgba(29,29,27,0.07)",
        borderBottom: "1px solid rgba(29,29,27,0.07)",
        display: "grid",
        gridTemplateColumns: "repeat(4,1fr)",
        background: "#FAFAFA",
      }} className="arch-specs-grid">
        {SPECS.map(({ n, u, l }, i) => (
          <motion.div
            key={l}
            initial={{ opacity: 0, y: 16 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.7, delay: 0.1 * i, ease: "easeOut" }}
            style={{
              padding: "clamp(24px,4vh,40px) clamp(20px,3vw,40px)",
              borderRight: i < 3 ? "1px solid rgba(29,29,27,0.07)" : "none",
              display: "flex", flexDirection: "column", gap: 6,
            }}
          >
            <div style={{
              fontFamily: "Cormorant Garamond,serif",
              fontSize: "clamp(24px,3vw,40px)", fontWeight: 300,
              color: DARK, lineHeight: 1,
            }}>
              {n}
              {u && <span style={{
                fontFamily: "Jost,sans-serif",
                fontSize: "clamp(12px,1.2vw,16px)", fontWeight: 200,
                color: PEARL, marginLeft: 4,
              }}>{u}</span>}
            </div>
            <div style={{
              fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.15em", color: "#767676", lineHeight: 1.5,
            }}>
              {l}
            </div>
          </motion.div>
        ))}
      </div>

      {/* ── Row 3: Facade + night image ────────────────────────────── */}
      <div style={{
        display: "grid", gridTemplateColumns: "1fr 1fr",
        minHeight: "50vh",
      }} className="arch-grid-2">

        {/* Left — descriptive text */}
        <div style={{
          padding: "clamp(40px,7vh,80px) clamp(32px,5vw,80px)",
          display: "flex", flexDirection: "column", justifyContent: "center",
          background: "#fff",
        }}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.3, ease: "easeOut" }}
          >
            <div style={{
              fontFamily: "Jost,sans-serif", fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.4em", textTransform: "uppercase",
              color: PEARL, marginBottom: 20,
            }}>
              The façade · A dual identity
            </div>
            <h3 style={{
              fontFamily: "Cormorant Garamond,serif",
              fontStyle: "italic", fontWeight: 300,
              fontSize: "clamp(22px,2.8vw,38px)", color: DARK,
              lineHeight: 1.2, marginBottom: 20, letterSpacing: "-0.01em",
            }}>
              Glass toward the Gulf.<br />Stone toward the desert.
            </h3>
            <p style={{
              fontFamily: "Jost,sans-serif", fontWeight: 300,
              fontSize: "clamp(13px,1.05vw,14px)", color: "#767676",
              lineHeight: 1.9, marginBottom: 16,
            }}>
              Three glass facades face north, east, and west — maximising views 
              across Kuwait Bay and the Arabian Gulf. The south wall — 84,000m² 
              of Jura limestone — turns its back to the desert sun, minimising 
              solar heat gain across all 62 office floors.
            </p>
            <p style={{
              fontFamily: "Jost,sans-serif", fontWeight: 300,
              fontSize: "clamp(13px,1.05vw,14px)", color: "#767676",
              lineHeight: 1.9,
            }}>
              The deep-angled windows carved into the south wall angle 
              obliquely — framing views across the city and peninsula while 
              blocking direct sunlight entirely. Every office is north-facing. 
              No tenant faces the desert.
            </p>
          </motion.div>
        </div>

        {/* Right — night tower image */}
        <div style={{ position: "relative", overflow: "hidden", minHeight: 320 }}>
          <motion.img
            src="/assets/tower-aerial-night.jpg"
            alt="Al Hamra Tower at night — Kuwait City skyline"
            style={{
              y: imgY,
              width: "100%", height: "115%",
              objectFit: "cover", objectPosition: "center",
              display: "block",
            }}
          />
        </div>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .arch-grid-1  { grid-template-columns: 1fr !important; }
          .arch-grid-2  { grid-template-columns: 1fr !important; }
          .arch-specs-grid { grid-template-columns: 1fr 1fr !important; }
        }
        @media (max-width: 480px) {
          .arch-specs-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </section>
  );
}
