import { useRef } from "react";
import { motion, useScroll, useTransform, useInView } from "framer-motion";
import { PatternBackground } from "@/components/shared/PatternBand";
import { useI18n } from "@/lib/i18n";

/* ── Architecture Section — Homepage ──────────────────────────────────
   The architectural story of the form: how the geometry responds to
   Kuwait's sun, the desert, the Gulf, and the city. Bilingual EN/AR
   with luxury MSA register (not literal translation).
──────────────────────────────────────────────────────────────────────── */

const PEARL = "#C8B99A";
const GULF  = "#2A5F7A";
const DARK  = "#1D1D1B";
const FONT  = "'Century Gothic','AppleGothic','Gill Sans MT','Gill Sans',Futura,'Trebuchet MS',sans-serif";

const CONTENT = {
  en: {
    kicker: "SOM Architecture · 2006–2011",
    headlineA: "A form born from",
    headlineB: "sun, wind, and the Gulf.",
    body1: "The Al Hamra Tower's geometry was generated by a single decisive act: subtracting a spiraling quadrant from a simple prismatic volume, then rotating it incrementally at each higher level. The result is two hyperbolic paraboloid walls — the iconic flared ribbons — that extend the full 412 metres of the building's height.",
    body2Pre: "The transparent glass envelope faces north, west, and east — toward the Arabian Gulf. The monolithic stone wall faces south — shielding every office from Kuwait's desert sun. Architecture and engineering evolved together. The structure ",
    body2Em: "is",
    body2Post: " the form.",
    quote: "\"Like an enshrouded figure with its delicate glass veil, the Tower provides spectacular views over much of Kuwait and across the Arabian Gulf.\"",
    credit: "Skidmore, Owings & Merrill LLP",
    milestonesKicker: "Construction Milestones",
    milestones: [
      { y: "2005", e: "Concept by SOM San Francisco" },
      { y: "2007", e: "Ground breaking · piling begins" },
      { y: "2009", e: "Topping out at 412.6 m" },
      { y: "2010", e: "Façade installation completed" },
      { y: "2011", e: "Building inaugurated" },
    ],
    specs: [
      { n: "258,000", u: "m²", l: "Jura limestone cladding — world record" },
      { n: "195,000", u: "m³", l: "Reinforced concrete poured" },
      { n: "289",     u: "",   l: "Foundation piles, 1.2m diameter" },
      { n: "55,000",  u: "m²", l: "Curtain wall glass panels" },
    ],
    facadeKicker: "The façade · A dual identity",
    facadeHeadingA: "Glass toward the Gulf.",
    facadeHeadingB: "Stone toward the desert.",
    facadeBody1: "Three glass facades face north, east, and west — maximising views across Kuwait Bay and the Arabian Gulf. The south wall — 84,000m² of Jura limestone — turns its back to the desert sun, minimising solar heat gain across all 62 office floors.",
    facadeBody2: "The deep-angled windows carved into the south wall angle obliquely — framing views across the city and peninsula while blocking direct sunlight entirely. Every office is north-facing. No tenant faces the desert.",
    renderAlt: "Al Hamra Tower architectural render",
    nightAlt: "Al Hamra Tower at night — Kuwait City skyline",
  },
  ar: {
    kicker: "هندسة SOM · ٢٠٠٦–٢٠١١",
    headlineA: "شكلٌ تنسّمَته الشمس",
    headlineB: "والرياح والخليج.",
    body1: "وُلِدت هندسة برج الحمراء من فعلٍ معماريٍّ واحدٍ حاسم: اقتطاعُ قطاعٍ ربعيٍّ حلزونيٍّ من حجمٍ موشوريٍّ بسيط، ثمّ تدويرُه تدريجاً عند كلّ مستوى أعلى. والنتيجة جداران مكافئان زائديّان — الشريطان المنسابان الأيقونيّان — يمتدّان على ارتفاع البرج الكامل البالغ ٤١٢ متراً.",
    body2Pre: "ينفتح الغلاف الزجاجيّ الشفّاف نحو الشمال والغرب والشرق — صوب الخليج العربي. وينتصب الجدار الحجريّ المتراصّ جنوباً — حاجباً عن كلّ مكتبٍ شمسَ صحراء الكويت. تطوّرت العمارة والهندسة معاً، حتى صار الهيكل ",
    body2Em: "هو",
    body2Post: " الشكل ذاته.",
    quote: "«كهيئةٍ محتجبةٍ خلف حجابها الزجاجيّ الرقيق، يهب البرج إطلالاتٍ مدهشة على معظم الكويت وعبر امتداد الخليج العربي.»",
    credit: "سكيدمور، أوينغز آند ميريل ش.ذ.م.م.",
    milestonesKicker: "محطّات البناء",
    milestones: [
      { y: "٢٠٠٥", e: "تصوُّر المشروع — SOM سان فرانسيسكو" },
      { y: "٢٠٠٧", e: "وضع حجر الأساس · بدء أعمال الركائز" },
      { y: "٢٠٠٩", e: "بلوغ القمّة عند ٤١٢٫٦ م" },
      { y: "٢٠١٠", e: "اكتمال تركيب الواجهة" },
      { y: "٢٠١١", e: "افتتاح البرج" },
    ],
    specs: [
      { n: "٢٥٨٬٠٠٠", u: "م²", l: "كسوة حجر جورا الجيري — رقمٌ قياسيٌّ عالميّ" },
      { n: "١٩٥٬٠٠٠", u: "م³", l: "حجم الخرسانة المسلّحة المصبوبة" },
      { n: "٢٨٩",     u: "",   l: "ركيزة أساسٍ بقطر ١٫٢ م" },
      { n: "٥٥٬٠٠٠",  u: "م²", l: "ألواح زجاج الواجهة الجداريّة" },
    ],
    facadeKicker: "الواجهة · هويّةٌ مزدوجة",
    facadeHeadingA: "زجاجٌ نحو الخليج.",
    facadeHeadingB: "حجرٌ نحو الصحراء.",
    facadeBody1: "تطلّ ثلاث واجهاتٍ زجاجيّة شمالاً وشرقاً وغرباً — لتفتح أوسع إطلالاتٍ على جون الكويت والخليج العربي. أمّا الجدار الجنوبيّ — ٨٤٬٠٠٠ م² من حجر جورا الجيريّ — فيُدير ظهره لشمس الصحراء، مقلِّصاً اكتساب الحرارة الشمسيّة عبر طوابق المكاتب الـ ٦٢ كافّة.",
    facadeBody2: "النوافذ ذات الانحدار العميق المنحوتة في الجدار الجنوبيّ تميل مائلةً — فتُؤطِّر إطلالات المدينة وشبه الجزيرة، وتحجب أشعّة الشمس المباشرة حجباً تامّاً. كلّ مكتبٍ يفتح نحو الشمال؛ ولا مستأجرٌ يواجه الصحراء.",
    renderAlt: "تصوّر معماري لبرج الحمراء",
    nightAlt: "برج الحمراء ليلاً — أفق مدينة الكويت",
  },
} as const;

export function Architecture() {
  const { lang } = useI18n();
  const c = CONTENT[lang];
  const ref    = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });

  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const imgY = useTransform(scrollYProgress, [0, 1], ["0%", "12%"]);

  // RTL-aware: quote bar flips to right edge in Arabic;
  // milestone year column separator also flips to the opposite side.
  const isAr = lang === "ar";

  return (
    <PatternBackground opacity={0.3} style={{ background: "#fff", overflow: "hidden" }}>
      <div ref={ref}>

      {/* ── Row 1: Full story + render ─────────────────────────────── */}
      <div style={{
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        minHeight: "70vh",
      }} className="arch-grid-1">

        {/* Left — SOM render, dusk purple sky */}
        <motion.div
          style={{ position: "relative", overflow: "hidden", background: "#0c0b09" }}
        >
          <motion.img
            src="/lovable-uploads/46052915-521a-44ca-bbd4-d770e159f7fa.png"
            alt={c.renderAlt}
            style={{ y: imgY, width: "100%", height: "130%",
              objectFit: "cover", objectPosition: "center center", display: "block" }}
          />
        </motion.div>

        {/* Right — The Form Story */}
        <div style={{
          padding: "clamp(48px,8vh,100px) clamp(32px,5vw,80px)",
          display: "flex", flexDirection: "column", justifyContent: "center",
        }}>
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={inView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.8, ease: [0.16,1,0.3,1] }}
          >
            {/* Kicker */}
            <div style={{
              display: "flex", alignItems: "center", gap: 14, marginBottom: 28,
              fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.45em", textTransform: "uppercase", color: PEARL,
            }}>
              <span style={{ width: 32, height: 1,
                background: `linear-gradient(to right, ${PEARL}, #D4CFC9)`, flexShrink: 0 }} />
              {c.kicker}
            </div>

            <h2 style={{
              fontFamily: FONT,
              fontWeight: 300, fontSize: "clamp(28px,3.8vw,52px)",
              color: DARK, lineHeight: 1.1, letterSpacing: "-0.01em", marginBottom: 24,
            }}>
              {c.headlineA}<br />{c.headlineB}
            </h2>

            <p style={{
              fontFamily: FONT, fontWeight: 300,
              fontSize: "clamp(13px,1.1vw,15px)", color: "#5a5a58",
              lineHeight: 1.9, marginBottom: 20,
            }}>
              {c.body1}
            </p>
            <p style={{
              fontFamily: FONT, fontWeight: 300,
              fontSize: "clamp(13px,1.1vw,15px)", color: "#5a5a58",
              lineHeight: 1.9, marginBottom: 36,
            }}>
              {c.body2Pre}<em>{c.body2Em}</em>{c.body2Post}
            </p>

            {/* Quote from SOM paper — bar flips to right edge in AR */}
            <div style={{
              borderLeft: isAr ? "none" : `2px solid ${PEARL}`,
              borderRight: isAr ? `2px solid ${PEARL}` : "none",
              paddingLeft: isAr ? 0 : 20,
              paddingRight: isAr ? 20 : 0,
              marginBottom: 36,
            }}>
              <p style={{
                fontFamily: FONT, fontStyle: "italic",
                fontSize: "clamp(15px,1.4vw,18px)", color: DARK,
                lineHeight: 1.7, margin: 0,
              }}>
                {c.quote}
              </p>
              <div style={{
                fontFamily: FONT, fontSize: "10px",
                letterSpacing: "0.3em", textTransform: "uppercase",
                color: PEARL, marginTop: 12,
              }}>
                {c.credit}
              </div>
            </div>

            {/* Construction Timeline */}
            <div>
              <div style={{
                fontFamily: FONT,
                fontSize: "10px", letterSpacing: "0.3em", textTransform: "uppercase",
                color: GULF, marginBottom: 14,
              }}>
                {c.milestonesKicker}
              </div>
              <div style={{
                display: "grid",
                gridTemplateColumns: "auto 1fr",
                rowGap: 10, columnGap: 18,
              }}>
                {c.milestones.map(({ y, e }) => (
                  <div key={y} style={{ display: "contents" }}>
                    <span style={{
                      fontFamily: FONT,
                      fontSize: "11px", letterSpacing: "0.18em",
                      color: GULF, fontWeight: 500,
                      // In LTR, year sits left of event with right separator.
                      // In RTL, the visual order reverses naturally;
                      // the separator must move to the opposite edge.
                      borderRight: isAr ? "none" : `1px solid rgba(42,95,122,0.18)`,
                      borderLeft: isAr ? `1px solid rgba(42,95,122,0.18)` : "none",
                      paddingRight: isAr ? 0 : 18,
                      paddingLeft: isAr ? 18 : 0,
                    }}>
                      {y}
                    </span>
                    <span style={{
                      fontFamily: FONT,
                      fontSize: "12px", color: DARK,
                      letterSpacing: "0.04em", lineHeight: 1.5,
                    }}>
                      {e}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </div>

      {/* ── Row 2: Material specs strip ────────────────────────────── */}
      <div style={{
        borderTop: "1px solid rgba(29,29,27,0.07)",
        borderBottom: "1px solid rgba(29,29,27,0.07)",
        display: "grid",
        gridTemplateColumns: "repeat(4,1fr)",
        background: "#FAFAFA",
      }} className="arch-specs-grid">
        {c.specs.map(({ n, u, l }, i) => (
          <motion.div
            key={l}
            initial={{ opacity: 0, y: 16 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.7, delay: 0.1 * i, ease: "easeOut" }}
            style={{
              padding: "clamp(24px,4vh,40px) clamp(20px,3vw,40px)",
              borderRight: i < 3 ? "1px solid rgba(29,29,27,0.07)" : "none",
              display: "flex", flexDirection: "column", gap: 6,
            }}
          >
            <div style={{
              fontFamily: FONT,
              fontSize: "clamp(24px,3vw,40px)", fontWeight: 300,
              color: DARK, lineHeight: 1,
            }}>
              {n}
              {u && <span style={{
                fontFamily: FONT,
                fontSize: "clamp(12px,1.2vw,16px)", fontWeight: 200,
                color: PEARL, marginLeft: 4,
              }}>{u}</span>}
            </div>
            <div style={{
              fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.15em", color: "#6B6B6B", lineHeight: 1.5,
            }}>
              {l}
            </div>
          </motion.div>
        ))}
      </div>

      {/* ── Row 3: Facade + night image ────────────────────────────── */}
      <div style={{
        display: "grid", gridTemplateColumns: "1fr 1fr",
        minHeight: "50vh",
      }} className="arch-grid-2">

        {/* Left — descriptive text */}
        <div style={{
          padding: "clamp(40px,7vh,80px) clamp(32px,5vw,80px)",
          display: "flex", flexDirection: "column", justifyContent: "center",
          background: "#fff",
        }}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.3, ease: "easeOut" }}
          >
            <div style={{
              fontFamily: FONT, fontSize: "clamp(10px,0.85vw,11px)",
              letterSpacing: "0.4em", textTransform: "uppercase",
              color: PEARL, marginBottom: 20,
            }}>
              {c.facadeKicker}
            </div>
            <h3 style={{
              fontFamily: FONT,
              fontWeight: 300,
              fontSize: "clamp(22px,2.8vw,38px)", color: DARK,
              lineHeight: 1.2, marginBottom: 20, letterSpacing: "-0.01em",
            }}>
              {c.facadeHeadingA}<br />{c.facadeHeadingB}
            </h3>
            <p style={{
              fontFamily: FONT, fontWeight: 300,
              fontSize: "clamp(13px,1.05vw,14px)", color: "#6B6B6B",
              lineHeight: 1.9, marginBottom: 16,
            }}>
              {c.facadeBody1}
            </p>
            <p style={{
              fontFamily: FONT, fontWeight: 300,
              fontSize: "clamp(13px,1.05vw,14px)", color: "#6B6B6B",
              lineHeight: 1.9,
            }}>
              {c.facadeBody2}
            </p>
          </motion.div>
        </div>

        {/* Right — night tower image */}
        <div style={{ position: "relative", overflow: "hidden", minHeight: 320 }}>
          <motion.img
            src="/assets/tower-aerial-night.jpg"
            alt={c.nightAlt}
            style={{
              y: imgY,
              width: "100%", height: "115%",
              objectFit: "cover", objectPosition: "center",
              display: "block",
            }}
          />
        </div>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .arch-grid-1  { grid-template-columns: 1fr !important; }
          .arch-grid-2  { grid-template-columns: 1fr !important; }
          .arch-specs-grid { grid-template-columns: 1fr 1fr !important; }
        }
        @media (max-width: 480px) {
          .arch-specs-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
      </div>
    </PatternBackground>
  );
}
