import { useRef } from "react";
import { motion, useInView } from "framer-motion";

/* ── FounderQuote ─────────────────────────────────────────────────────
   Inspired by burjkhalifa.ae/the-tower/ — which opens with a founder
   quote that establishes the building's meaning before any stats.
   Adapted for Al Hamra: the SOM architectural quote serves the same
   role here — the geometry IS the story.
   
   Layout: two-column, big italic serif quote on left, render on right.
   Not a "section" in our brochure sense — a literary interlude.
──────────────────────────────────────────────────────────────────────── */

const PEARL      = "#C8B99A";
const PEARL_TEXT = "#8B6E3E";
const DARK       = "#1D1D1B";
const CG         = "'Century Gothic','AppleGothic','Gill Sans MT','Gill Sans',Futura,'Trebuchet MS',sans-serif";

export function FounderQuote() {
  const ref    = useRef<HTMLElement>(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section
      ref={ref}
      style={{
        background: "#fff",
        padding: "clamp(80px,12vh,140px) clamp(28px,6vw,96px)",
        position: "relative",
        overflow: "hidden",
      }}
    >
      <div style={{
        maxWidth: 1280, margin: "0 auto",
        display: "grid",
        gridTemplateColumns: "1.15fr 1fr",
        gap: "clamp(48px,6vw,96px)",
        alignItems: "center",
      }} className="fq-grid">

        {/* ── LEFT: The quote ───────────────────────────────────── */}
        <div>
          {/* Kicker */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6 }}
            style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 36 }}
          >
            <span style={{ width: 32, height: 1, background: `linear-gradient(to right, ${PEARL}, #D4CFC9)` }} />
            <span style={{
              fontFamily: CG, fontSize: "11px", letterSpacing: "0.4em",
              textTransform: "uppercase", color: PEARL_TEXT,
            }}>
              The Architectural Gesture
            </span>
          </motion.div>

          {/* Giant opening quote mark */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={inView ? { opacity: 0.18, scale: 1 } : {}}
            transition={{ duration: 1.2, delay: 0.1 }}
            aria-hidden="true"
            style={{
              fontFamily: "Georgia, 'Times New Roman', serif",
              fontSize: "clamp(120px,14vw,180px)", fontWeight: 300,
              color: PEARL, lineHeight: 0.6,
              marginBottom: "-12px",
              marginLeft: "-4px",
              userSelect: "none",
            }}
          >
            &ldquo;
          </motion.div>

          {/* The quote */}
          <motion.blockquote
            initial={{ opacity: 0, y: 24 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.9, delay: 0.25, ease: [0.16, 1, 0.3, 1] }}
            style={{ margin: 0, padding: 0 }}
          >
            <p style={{
              fontFamily: "Georgia, 'Times New Roman', serif",
              fontWeight: 300,
              fontSize: "clamp(22px,2.6vw,38px)",
              color: DARK,
              lineHeight: 1.35,
              letterSpacing: "-0.01em",
              fontStyle: "italic",
              margin: 0,
              maxWidth: 620,
            }}>
              The building geometry is generated by a spiralling slice
              subtracted from a simple prismatic volume &mdash; architectural
              expression through structural form on a grand scale.
            </p>

            {/* Attribution */}
            <motion.footer
              initial={{ opacity: 0 }}
              animate={inView ? { opacity: 1 } : {}}
              transition={{ duration: 0.7, delay: 0.8 }}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 16,
                marginTop: 40,
              }}
            >
              <span style={{ width: 24, height: 1, background: PEARL }} aria-hidden="true" />
              <div>
                <div style={{
                  fontFamily: CG, fontSize: "12px", fontWeight: 500,
                  letterSpacing: "0.18em", textTransform: "uppercase",
                  color: DARK,
                }}>
                  Mark Sarkisian
                </div>
                <div style={{
                  fontFamily: CG, fontSize: "10px",
                  letterSpacing: "0.22em", textTransform: "uppercase",
                  color: PEARL_TEXT,
                  marginTop: 3,
                }}>
                  Skidmore, Owings &amp; Merrill &middot; Lead Architect
                </div>
              </div>
            </motion.footer>
          </motion.blockquote>
        </div>

        {/* ── RIGHT: Portrait tower image ───────────────────────── */}
        <motion.div
          initial={{ opacity: 0, x: 24 }}
          animate={inView ? { opacity: 1, x: 0 } : {}}
          transition={{ duration: 1.1, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
          style={{
            position: "relative",
            aspectRatio: "3/4",
            background: "#0c0b09",
            overflow: "hidden",
          }}
          className="fq-image"
        >
          <img
            loading="lazy"
            src="/assets/tower-overview-banner.jpg"
            alt="Al Hamra Tower — SOM architectural render showing the spiralling subtracted form"
            style={{
              width: "100%", height: "100%", display: "block",
              objectFit: "cover", objectPosition: "center 20%",
            }}
          />
          {/* Pearl gradient overlay bottom */}
          <div style={{
            position: "absolute", bottom: 0, left: 0, right: 0, height: "35%",
            background: `linear-gradient(to top, rgba(12,11,9,0.7) 0%, transparent 100%)`,
            pointerEvents: "none",
          }} aria-hidden="true" />
          {/* Caption */}
          <div style={{
            position: "absolute", bottom: 20, left: 20,
            fontFamily: CG, fontSize: "10px",
            letterSpacing: "0.3em", textTransform: "uppercase",
            color: PEARL,
          }}>
            412.6 m &middot; Kuwait City
          </div>
        </motion.div>

      </div>

      <style>{`
        @media (max-width: 900px) {
          .fq-grid {
            grid-template-columns: 1fr !important;
            gap: 48px !important;
          }
          .fq-image { aspect-ratio: 4/5 !important; }
        }
      `}</style>
    </section>
  );
}
